import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Renames the gate-management `users` table to `gate_users` and adds the
 * nullable `user_id` link column pointing at the (not yet created) global
 * `users` mirror table.
 *
 * MUST run BEFORE 1775736200000-CreateGlobalUsersTable, otherwise the `users`
 * name is still taken and the two tables collide.
 *
 * PostgreSQL carries foreign keys across a table rename automatically (every
 * FK that referenced `users`.`id` now references `gate_users`.`id`, keeping its
 * original constraint name), but index and constraint NAMES are not updated by
 * the rename. Any name that embeds the old table name is rewritten explicitly
 * below so it cannot collide with the new `users` table's own indexes.
 */
export class RenameUsersToGateUsers1775736000000 implements MigrationInterface {
  name = 'RenameUsersToGateUsers1775736000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const hasUsers = await queryRunner.hasTable('users');
    const hasGateUsers = await queryRunner.hasTable('gate_users');

    if (hasUsers && hasGateUsers) {
      // Almost certainly synchronize created an empty `gate_users` from the
      // updated entity while the real data still sits in `users`. Renaming now
      // would fail anyway; fail loudly rather than silently stranding the data.
      throw new Error(
        'Both "users" and "gate_users" exist. This usually means TypeORM ' +
          'synchronize created an empty "gate_users" table before this migration ' +
          'ran. Inspect both tables, drop the empty one, and re-run with ' +
          'synchronize disabled.',
      );
    }

    if (!hasUsers && !hasGateUsers) {
      throw new Error(
        'Neither "users" nor "gate_users" exists; cannot perform the rename.',
      );
    }

    if (hasUsers) {
      await queryRunner.query(`ALTER TABLE "users" RENAME TO "gate_users"`);

      // Rewrite index/constraint names that still embed the old table name.
      // Hash-based names generated by synchronize (IDX_/PK_/UQ_ + hash) do not
      // contain the table name and are deliberately left alone.
      await queryRunner.query(`
        DO $$
        DECLARE
          idx RECORD;
        BEGIN
          FOR idx IN
            SELECT c.relname AS name
            FROM pg_index i
            JOIN pg_class c ON c.oid = i.indexrelid
            JOIN pg_class t ON t.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
            WHERE t.relname = 'gate_users'
              AND n.nspname = 'public'
              AND c.relname LIKE '%users%'
              AND c.relname NOT LIKE '%gate_users%'
          LOOP
            EXECUTE format(
              'ALTER INDEX public.%I RENAME TO %I',
              idx.name,
              replace(idx.name, 'users', 'gate_users')
            );
          END LOOP;
        END $$;
      `);
    }

    // Add the link column to the global `users` mirror table. Nullable because
    // it is unpopulated in Phase 1; unique so a global identity maps to at most
    // one gate user. NULLs are not compared for uniqueness in PostgreSQL, so
    // any number of unlinked rows is allowed.
    const table = await queryRunner.getTable('gate_users');
    const hasUserId = table?.columns.find((col) => col.name === 'user_id');

    if (!hasUserId) {
      await queryRunner.query(
        `ALTER TABLE "gate_users" ADD "user_id" uuid`,
      );
      await queryRunner.query(
        `CREATE UNIQUE INDEX "UQ_gate_users_user_id" ON "gate_users" ("user_id")`,
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const hasGateUsers = await queryRunner.hasTable('gate_users');
    if (!hasGateUsers) {
      return;
    }

    // Reverse order: drop the added column first, then rename the table back.
    await queryRunner.query(
      `DROP INDEX IF EXISTS "public"."UQ_gate_users_user_id"`,
    );

    const table = await queryRunner.getTable('gate_users');
    if (table?.columns.find((col) => col.name === 'user_id')) {
      await queryRunner.query(`ALTER TABLE "gate_users" DROP COLUMN "user_id"`);
    }

    // The global `users` mirror table must be gone before the name is reclaimed;
    // its own migration (1775736200000) runs down() first in reverse order.
    const hasUsers = await queryRunner.hasTable('users');
    if (hasUsers) {
      throw new Error(
        'Cannot rename "gate_users" back to "users": a "users" table already ' +
          'exists. Revert 1775736200000-CreateGlobalUsersTable first.',
      );
    }

    // Restore the index/constraint names that were rewritten in up().
    await queryRunner.query(`
      DO $$
      DECLARE
        idx RECORD;
      BEGIN
        FOR idx IN
          SELECT c.relname AS name
          FROM pg_index i
          JOIN pg_class c ON c.oid = i.indexrelid
          JOIN pg_class t ON t.oid = i.indrelid
          JOIN pg_namespace n ON n.oid = t.relnamespace
          WHERE t.relname = 'gate_users'
            AND n.nspname = 'public'
            AND c.relname LIKE '%gate_users%'
        LOOP
          EXECUTE format(
            'ALTER INDEX public.%I RENAME TO %I',
            idx.name,
            replace(idx.name, 'gate_users', 'users')
          );
        END LOOP;
      END $$;
    `);

    await queryRunner.query(`ALTER TABLE "gate_users" RENAME TO "users"`);
  }
}
